{% set name = "kisiac" %}
{% set version = "1.4.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ffaddcbedc4f0da4dbcb2de0b6b56ca9d5d34a77e6c5d0ed084e0576ff3323c7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - kisiac = kisiac.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - hatchling
  run:
    - python >={{ python_min }}
    - pyyaml >=6.0.3,<7
    - jinja2 >=3.1.6,<4
    - gitpython >=3.1.45,<4
    - pyfstab >=0.2.0,<0.3
    - inquirer >=3.4.1,<4
    - humanfriendly >=10.0,<11
    - yte >=1.9.0,<2

test:
  commands:
    - pip check
    - kisiac --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/kisiac/kisiac
  summary: A "keep it simple" infrastructure as code tool
  description: |
    Infrastructure as code is a convenient approach to make the configuration of
    machines predictable and transparent. Yet, approaches like ansible are, while being
    extremely flexible, overly complex for small scaled setups. Kisiac shall provide
    a simpler alternative that suffices for single machines or less complex
    infrastructure.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - johanneskoester
